openapi: '3.0.0'
info:
  version: 1.0.0
  title: Workflow In-Spiration
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /scores:
    get:
      summary: List all scores
      operationId: listScores
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: An paged array of scores
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Scores'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create score
      operationId: createScore
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /scores/{scoreId}:
    get:
      summary: Get score details
      operationId: showScoreById
      parameters:
        - name: scoreId
          in: path
          required: true
          description: The id of the score to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Scores'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /athletes:
    get:
      summary: List all athletes
      operationId: listAthletes
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: An paged array of athletes
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Athletes'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create athlete
      operationId: createAthlete
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /athletes/{athleteId}:
    get:
      summary: Get athlete details
      operationId: showAthleteById
      parameters:
        - name: athleteId
          in: path
          required: true
          description: The id of the athlete to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Athletes'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Score:
      required:
        - id
        - athleteId
        - value
      properties:
        id:
          type: integer
          format: int64
        athleteId:
          type: integer
          format: int64
        value:
          type: number
          format: float
        notes:
          type: string
    Scores:
      type: array
      items:
        $ref: '#/components/schemas/Score'
    Athlete:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        division:
          type: string
    Athletes:
      type: array
      items:
        $ref: '#/components/schemas/Athlete'
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string